-- MIMOS Academy PMS — consolidated Supabase installer
-- Target project: frzyodxqcvxivtukvdqj
-- Run once in Supabase Dashboard > SQL Editor on the NEW/EMPTY project.
-- Ordered equivalent of migrations 001..012.

begin;

-- 001 extensions
create extension if not exists pgcrypto;
create extension if not exists citext;

-- 002 application types
create type public.app_role as enum ('admin','staff','viewer');
create type public.n_a_state as enum ('not_applicable','provided','pending','unknown');

-- 003 lookup/master
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,email citext unique,full_name text not null,role public.app_role not null default 'staff',staff_id bigint,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.account_type (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.staff_role (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.sector (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_type (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_method (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.quotation_type (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.quotation_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.programme_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.opportunity_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.action_item_status (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_terms (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,days integer check(days>=0),description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.speed_to_market (id bigint generated always as identity primary key,code varchar(10) not null unique,name varchar(50) not null,quarter varchar(10),year integer check(year between 2000 and 2200),description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.programme_category (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.service_type (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.revenue_type (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.account (id bigint generated always as identity primary key,code varchar(20) not null unique,name varchar(100) not null,description varchar(255),account_type_id bigint references public.account_type(id) on delete set null,is_active boolean not null default true,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint);
create table public.staff (id bigint generated always as identity primary key,staff_number varchar(50),full_name varchar(100) not null,email citext not null unique,phone varchar(50),role_id bigint references public.staff_role(id) on delete set null,is_active boolean not null default true,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null);
create table public.client (id bigint generated always as identity primary key,company_name varchar(255) not null,registration_number varchar(100),address text,sector_id bigint references public.sector(id) on delete set null,is_active boolean not null default true,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null);
create table public.client_contact (id bigint generated always as identity primary key,client_id bigint not null references public.client(id) on delete cascade,contact_name varchar(100) not null,contact_email varchar(255),contact_phone varchar(50),contact_designation varchar(100),is_primary boolean not null default false,is_active boolean not null default true,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null);
insert into public.account_type(code,name,description) values ('MSSB','MIMOS Services Sdn Bhd','Primary operating subsidiary'),('MB','MIMOS Berhad','Parent company / holding entity'),('MIMOS','MIMOS Group','Generic MIMOS entity'),('MH','MIMOS Holdings','Investment holding company'),('OTHER','Other','Third party or external entity') on conflict(code) do nothing;
insert into public.staff_role(code,name,description) values ('MASB_TEAM','MASB Team','Core MIMOS Academy team member'),('SUPER_ADMIN','Super Admin','System administrator'),('MANAGER','Manager','Team manager'),('PIC','Person In Charge','Programme owner'),('SALES','Sales','Business development'),('FINANCE','Finance','Financial operations'),('TRAINER','Trainer','Training delivery'),('INTERN','Intern','Temporary staff') on conflict(code) do nothing;
insert into public.sector(code,name) values ('GOVT','Government'),('PRIVATE','Private Sector'),('INTERCO','Intercompany'),('ACADEMIC','Academic'),('NGO','NGO'),('OTHER','Other') on conflict(code) do nothing;

-- 004 programme/commercial
create table public.programme (id bigint generated always as identity primary key,programme_code varchar(50),title varchar(500) not null,description text,client_id bigint not null references public.client(id) on delete restrict,training_type_id bigint references public.training_type(id) on delete set null,programme_category_id bigint references public.programme_category(id) on delete set null,programme_status_id bigint references public.programme_status(id) on delete set null,account_id bigint references public.account(id) on delete set null,account_manager_id bigint references public.staff(id) on delete set null,pic_id bigint references public.staff(id) on delete set null,duration_days numeric(5,2) check(duration_days is null or duration_days>=0),no_of_pax integer check(no_of_pax is null or no_of_pax>=0),start_date date,end_date date,total_revenue_excl_tax numeric(18,2) not null default 0,total_sst_amount numeric(18,2) not null default 0,total_revenue_incl_tax numeric(18,2) not null default 0,total_collected numeric(18,2) not null default 0,total_outstanding numeric(18,2) not null default 0,is_public_training boolean not null default false,is_in_house boolean not null default false,is_internal boolean not null default false,n_a_state public.n_a_state,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_programme_dates check(end_date is null or start_date is null or end_date>=start_date));
create unique index uq_programme_code_real on public.programme(programme_code) where programme_code is not null and programme_code<>'';
create index idx_programme_client on public.programme(client_id); create index idx_programme_status on public.programme(programme_status_id); create index idx_programme_dates on public.programme(start_date,end_date); create index idx_programme_match on public.programme(client_id,title,start_date,end_date);
create table public.quotation (id bigint generated always as identity primary key,quotation_no varchar(100) not null,revision varchar(20) not null default '0',programme_id bigint references public.programme(id) on delete set null,client_id bigint not null references public.client(id) on delete restrict,quotation_type_id bigint references public.quotation_type(id) on delete set null,training_type_id bigint references public.training_type(id) on delete set null,quotation_status_id bigint references public.quotation_status(id) on delete set null,account_manager_id bigint references public.staff(id) on delete set null,pic_id bigint references public.staff(id) on delete set null,account_id bigint references public.account(id) on delete set null,project_title varchar(500),duration_days numeric(5,2),no_of_unit integer,unit_price_excl_tax numeric(18,4),unit_price_incl_tax numeric(18,4),total_price_excl_tax numeric(18,2),total_price_incl_tax numeric(18,2),sst_amount numeric(18,2),sst_rate numeric(7,5) default .08,discount_percentage numeric(5,2) default 0,discount_amount numeric(18,2) default 0,final_price numeric(18,2),currency varchar(3) not null default 'MYR',quotation_date date,valid_until date,pic_full_name varchar(100),pic_contact_no varchar(50),pic_email varchar(255),source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_quotation_sst_rate check(sst_rate between 0 and 1),constraint chk_quotation_discount check(discount_percentage between 0 and 100));
create index idx_quotation_programme on public.quotation(programme_id); create index idx_quotation_client on public.quotation(client_id); create index idx_quotation_date on public.quotation(quotation_date); create index idx_quotation_match on public.quotation(quotation_no,client_id,programme_id);
create table public.purchase_order (id bigint generated always as identity primary key,po_no varchar(100),po_reference varchar(100),programme_id bigint references public.programme(id) on delete set null,quotation_id bigint references public.quotation(id) on delete set null,client_id bigint not null references public.client(id) on delete restrict,account_id bigint references public.account(id) on delete set null,po_date date,po_value_excl_tax numeric(18,2),po_value_incl_tax numeric(18,2),sst_amount numeric(18,2),sst_rate numeric(7,5) default .08,currency varchar(3) not null default 'MYR',description text,po_status varchar(50),is_active boolean not null default true,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_po_sst_rate check(sst_rate between 0 and 1),constraint chk_po_value check(po_value_excl_tax is null or po_value_excl_tax>=0));
create index idx_po_programme on public.purchase_order(programme_id); create index idx_po_client on public.purchase_order(client_id); create index idx_po_date on public.purchase_order(po_date);
create table public.invoice (id bigint generated always as identity primary key,invoice_no varchar(100),invoice_reference varchar(100),programme_id bigint not null references public.programme(id) on delete restrict,quotation_id bigint references public.quotation(id) on delete set null,purchase_order_id bigint references public.purchase_order(id) on delete set null,client_id bigint not null references public.client(id) on delete restrict,account_id bigint references public.account(id) on delete set null,revenue_type_id bigint references public.revenue_type(id) on delete set null,payment_status_id bigint references public.payment_status(id) on delete set null,payment_terms_id bigint references public.payment_terms(id) on delete set null,payment_method_id bigint references public.payment_method(id) on delete set null,invoice_date date,due_date date,training_start_date date,training_end_date date,amount_excl_tax numeric(18,2),sst_amount numeric(18,2),sst_rate numeric(7,5) default .08,total_incl_tax numeric(18,2),amount_collected numeric(18,2) not null default 0,amount_outstanding numeric(18,2) not null default 0,currency varchar(3) not null default 'MYR',payment_date date,days_outstanding integer,quotation_no_ref varchar(100),po_no_ref varchar(100),is_placeholder boolean not null default false,is_cancelled boolean not null default false,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_invoice_dates check(training_end_date is null or training_start_date is null or training_end_date>=training_start_date),constraint chk_invoice_sst_rate check(sst_rate between 0 and 1));
create index idx_invoice_programme on public.invoice(programme_id); create index idx_invoice_client on public.invoice(client_id); create index idx_invoice_due_date on public.invoice(due_date); create index idx_invoice_status on public.invoice(payment_status_id); create index idx_invoice_import_batch on public.invoice(import_batch_id); create index idx_invoice_real_no on public.invoice(invoice_no) where invoice_no is not null and invoice_no<>'';
create table public.payment (id bigint generated always as identity primary key,payment_reference varchar(100),invoice_id bigint references public.invoice(id) on delete set null,programme_id bigint references public.programme(id) on delete set null,client_id bigint references public.client(id) on delete set null,payment_date date,amount numeric(18,2) not null default 0,sst_amount numeric(18,2) not null default 0,total_amount numeric(18,2) not null default 0,currency varchar(3) not null default 'MYR',amount_allocated numeric(18,2) not null default 0,amount_unallocated numeric(18,2) not null default 0,payment_method_id bigint references public.payment_method(id) on delete set null,payment_status_id bigint references public.payment_status(id) on delete set null,received_by_id bigint references public.staff(id) on delete set null,bank_reference varchar(100),cheque_no varchar(100),transaction_id varchar(150),notes text,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_payment_amount check(amount>=0),constraint chk_payment_alloc check(amount_allocated>=0 and amount_unallocated>=0));
create index idx_payment_invoice on public.payment(invoice_id); create index idx_payment_programme on public.payment(programme_id); create index idx_payment_date on public.payment(payment_date); create index idx_payment_status on public.payment(payment_status_id);

-- 005 operations/audit/import
create table public.opportunity (id bigint generated always as identity primary key,opportunity_code varchar(50),client_id bigint not null references public.client(id) on delete restrict,programme_id bigint references public.programme(id) on delete set null,opportunity_status_id bigint references public.opportunity_status(id) on delete set null,speed_to_market_id bigint references public.speed_to_market(id) on delete set null,sector_id bigint references public.sector(id) on delete set null,account_manager_id bigint references public.staff(id) on delete set null,salesman_id bigint references public.staff(id) on delete set null,project_title varchar(500) not null,project_description text,opportunity_type varchar(100),forecast_value numeric(18,2),probability_percentage numeric(5,2),weighted_value numeric(18,2),secured_value numeric(18,2),currency varchar(3) not null default 'MYR',expected_close_date date,actual_close_date date,po_date date,po_value numeric(18,2),is_government boolean default false,is_private boolean default false,is_interco boolean default false,remarks text,sector_remarks varchar(255),source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_opp_prob check(probability_percentage is null or probability_percentage between 0 and 100),constraint chk_opp_money check(coalesce(forecast_value,0)>=0 and coalesce(weighted_value,0)>=0 and coalesce(secured_value,0)>=0));
create index idx_opportunity_client on public.opportunity(client_id); create index idx_opportunity_programme on public.opportunity(programme_id); create index idx_opportunity_status on public.opportunity(opportunity_status_id); create index idx_opportunity_close on public.opportunity(expected_close_date); create index idx_opportunity_match on public.opportunity(client_id,project_title,forecast_value);
create table public.action_item (id bigint generated always as identity primary key,action_item_code varchar(50),client_id bigint references public.client(id) on delete set null,programme_id bigint references public.programme(id) on delete set null,opportunity_id bigint references public.opportunity(id) on delete set null,invoice_id bigint references public.invoice(id) on delete set null,assigned_to_id bigint references public.staff(id) on delete set null,action_item_status_id bigint references public.action_item_status(id) on delete set null,service_type_id bigint references public.service_type(id) on delete set null,service varchar(255),action_description text not null,person_in_charge varchar(100),person_email varchar(255),due_date date,completed_date date,potential_revenue numeric(18,2),currency varchar(3) not null default 'MYR',aging_days integer,priority varchar(20) not null default 'MEDIUM',notes text,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_action_priority check(priority in ('LOW','MEDIUM','HIGH','CRITICAL')),constraint chk_action_money check(potential_revenue is null or potential_revenue>=0));
create index idx_action_programme on public.action_item(programme_id); create index idx_action_status on public.action_item(action_item_status_id); create index idx_action_due on public.action_item(due_date); create index idx_action_assigned on public.action_item(assigned_to_id);
create table public.training_stat (id bigint generated always as identity primary key,programme_id bigint not null references public.programme(id) on delete restrict,training_type_id bigint references public.training_type(id) on delete set null,training_date date,training_name varchar(500),company_name varchar(255),training_category varchar(100),duration_days numeric(5,2),domain_code varchar(50),domain_name varchar(100),workshop_count integer default 0,training_count integer default 0,total_count integer default 0,bumiputera_count integer default 0,non_bumiputera_count integer default 0,total_charges_excl_tax numeric(18,2),sst_amount numeric(18,2),final_charges_incl_tax numeric(18,2),currency varchar(3) default 'MYR',source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null,constraint chk_training_counts check(workshop_count>=0 and training_count>=0 and total_count>=0 and bumiputera_count>=0 and non_bumiputera_count>=0));
create index idx_training_stat_programme on public.training_stat(programme_id); create index idx_training_stat_date on public.training_stat(training_date); create index idx_training_stat_match on public.training_stat(programme_id,training_date,domain_code);
create table public.participant (id bigint generated always as identity primary key,programme_id bigint not null references public.programme(id) on delete restrict,training_stat_id bigint references public.training_stat(id) on delete set null,full_name varchar(255) not null,identification_no varchar(50),cert_no varchar(100),email varchar(255),phone varchar(50),designation varchar(100),department varchar(100),organization varchar(255),is_bumiputera boolean,gender varchar(10),attendance_status varchar(50) default 'ATTENDED',cert_issued boolean default false,cert_issue_date date,source_file text,source_row_number integer,import_batch_id bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by bigint references public.staff(id) on delete set null,updated_by bigint references public.staff(id) on delete set null);
create index idx_participant_programme on public.participant(programme_id); create index idx_participant_name on public.participant(full_name); create index idx_participant_cert on public.participant(cert_no);
create table public.source_file (id bigint generated always as identity primary key,file_name varchar(255) not null,file_path varchar(500),file_hash varchar(64) not null,file_size_bytes bigint,file_type varchar(50),upload_date timestamptz not null default now(),uploaded_by_id bigint references public.staff(id) on delete set null,description text,is_processed boolean not null default false,processed_at timestamptz); create index idx_source_file_hash on public.source_file(file_hash);
create table public.import_batch (id bigint generated always as identity primary key,batch_code varchar(50) not null unique,source_file_id bigint references public.source_file(id) on delete set null,import_type varchar(50) not null,table_target varchar(100) not null,records_total integer default 0,records_inserted integer default 0,records_updated integer default 0,records_skipped integer default 0,records_failed integer default 0,records_in_review integer default 0,status varchar(50) default 'PENDING',start_time timestamptz,end_time timestamptz,notes text,error_log text,imported_by_id bigint references public.staff(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.stg_import_row (id bigint generated always as identity primary key,import_batch_id bigint not null references public.import_batch(id) on delete cascade,source_file_id bigint references public.source_file(id) on delete set null,source_row_number integer not null,entity_type varchar(100) not null,raw_data jsonb not null,normalized_data jsonb,business_key text,validation_status varchar(30) not null default 'PENDING',validation_errors jsonb not null default '[]'::jsonb,target_id bigint,created_at timestamptz not null default now()); create index idx_stg_batch on public.stg_import_row(import_batch_id); create index idx_stg_business_key on public.stg_import_row(entity_type,business_key);
create table public.data_conflict (id bigint generated always as identity primary key,import_batch_id bigint references public.import_batch(id) on delete set null,entity_type varchar(100) not null,source_row_number integer,existing_record_id bigint,conflict_type varchar(50) not null,source_data jsonb not null default '{}'::jsonb,existing_data jsonb not null default '{}'::jsonb,resolution varchar(30) default 'PENDING',resolved_record_id bigint,resolved_by uuid references auth.users(id) on delete set null,resolution_notes text,created_at timestamptz not null default now(),resolved_at timestamptz);
create table public.completeness_score (id bigint generated always as identity primary key,programme_id bigint references public.programme(id) on delete cascade,quotation_score numeric(5,2),po_score numeric(5,2),invoice_score numeric(5,2),payment_score numeric(5,2),delivery_score numeric(5,2),participant_score numeric(5,2),charges_score numeric(5,2),pic_score numeric(5,2),overall_score numeric(5,2),overall_status varchar(30),missing_components jsonb not null default '[]'::jsonb,na_components jsonb not null default '[]'::jsonb,evaluated_at timestamptz not null default now(),evaluated_by uuid references auth.users(id) on delete set null,unique(programme_id));
create table public.staff_alias (id bigint generated always as identity primary key,source_name text not null unique,staff_id bigint references public.staff(id) on delete set null,source_file text,created_at timestamptz not null default now());
create table public.client_alias (id bigint generated always as identity primary key,source_name text not null unique,client_id bigint references public.client(id) on delete set null,source_file text,created_at timestamptz not null default now());
create table public.audit_log (id bigint generated always as identity primary key,entity_type text not null,entity_id bigint,action text not null,actor_id uuid references auth.users(id) on delete set null,old_data jsonb,new_data jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.audit_history (id bigint generated always as identity primary key,programme_id bigint references public.programme(id) on delete set null,action text not null,entity text,description text,actor_id uuid references auth.users(id) on delete set null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index idx_audit_log_entity on public.audit_log(entity_type,entity_id); create index idx_audit_log_created on public.audit_log(created_at);

-- 006 triggers/functions
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['profiles','account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','import_batch'] loop execute format('drop trigger if exists %I on public.%I',t||'_updated_at',t); execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()',t||'_updated_at',t); end loop; end $$;
create or replace function public.fn_days_outstanding(p_due_date date,p_paid boolean default false) returns integer language sql stable as $$ select case when p_due_date is null or p_paid then null else current_date-p_due_date end $$;
create or replace function public.fn_weighted_forecast(p_forecast numeric,p_probability numeric) returns numeric language sql immutable as $$ select case when p_forecast is null or p_probability is null then null else round(p_forecast*greatest(least(p_probability,100),0)/100,2) end $$;
create or replace function public.fn_calc_sst(p_base_amount numeric,p_sst_rate numeric default .08) returns numeric language sql immutable as $$ select case when p_base_amount is null or p_sst_rate is null then null else round(p_base_amount*p_sst_rate,2) end $$;
create or replace function public.fn_calc_total_incl_sst(p_base_amount numeric,p_sst_amount numeric) returns numeric language sql immutable as $$ select case when p_base_amount is null then null else p_base_amount+coalesce(p_sst_amount,0) end $$;
create or replace function public.fn_refresh_invoice(p_invoice_id bigint) returns void language plpgsql security definer set search_path=public as $$ declare v_collected numeric; begin select coalesce(sum(coalesce(amount,0)),0) into v_collected from public.payment p left join public.payment_status ps on ps.id=p.payment_status_id where p.invoice_id=p_invoice_id and coalesce(ps.code,'') in ('PAID','COMPLETED','SUCCESS'); update public.invoice i set amount_collected=least(v_collected,coalesce(i.total_incl_tax,i.amount_excl_tax,0)),amount_outstanding=greatest(coalesce(i.total_incl_tax,i.amount_excl_tax,0)-least(v_collected,coalesce(i.total_incl_tax,i.amount_excl_tax,0)),0),days_outstanding=public.fn_days_outstanding(i.due_date,v_collected>=coalesce(i.total_incl_tax,i.amount_excl_tax,0)) where i.id=p_invoice_id; end; $$;
create or replace function public.trg_payment_refresh_invoice() returns trigger language plpgsql security definer set search_path=public as $$ begin if tg_op='DELETE' then perform public.fn_refresh_invoice(old.invoice_id); else perform public.fn_refresh_invoice(new.invoice_id); if tg_op='UPDATE' and old.invoice_id is distinct from new.invoice_id then perform public.fn_refresh_invoice(old.invoice_id); end if; end if; return coalesce(new,old); end; $$;
drop trigger if exists payment_refresh_invoice on public.payment; create trigger payment_refresh_invoice after insert or update or delete on public.payment for each row execute function public.trg_payment_refresh_invoice();
create or replace function public.fn_refresh_programme(p_programme_id bigint) returns void language plpgsql security definer set search_path=public as $$ begin update public.programme p set total_revenue_excl_tax=coalesce((select sum(i.amount_excl_tax) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0),total_sst_amount=coalesce((select sum(i.sst_amount) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0),total_revenue_incl_tax=coalesce((select sum(i.total_incl_tax) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0),total_collected=coalesce((select sum(i.amount_collected) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0),total_outstanding=coalesce((select sum(i.amount_outstanding) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0) where p.id=p_programme_id; end; $$;
create or replace function public.trg_invoice_refresh_programme() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.fn_refresh_programme(coalesce(new.programme_id,old.programme_id)); return coalesce(new,old); end; $$;
drop trigger if exists invoice_refresh_programme on public.invoice; create trigger invoice_refresh_programme after insert or update or delete on public.invoice for each row execute function public.trg_invoice_refresh_programme();
create or replace function public.fn_programme_completeness(p_programme_id bigint) returns numeric language plpgsql security definer set search_path=public as $$ declare n int:=0; s int:=0; begin select count(*) into n from public.quotation where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.purchase_order where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.invoice where programme_id=p_programme_id and not is_placeholder and not is_cancelled; if n>0 then s:=s+1; end if; select count(*) into n from public.payment where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.training_stat where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.participant where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.invoice where programme_id=p_programme_id and coalesce(amount_excl_tax,0)>0; if n>0 then s:=s+1; end if; select count(*) into n from public.programme where id=p_programme_id and pic_id is not null; if n>0 then s:=s+1; end if; insert into public.completeness_score(programme_id,overall_score,overall_status,evaluated_at) values(p_programme_id,round(s*12.5,2),case when s=8 then 'COMPLETE' when s>=6 then 'PARTIAL' else 'INCOMPLETE' end,now()) on conflict(programme_id) do update set overall_score=excluded.overall_score,overall_status=excluded.overall_status,evaluated_at=now(); return round(s*12.5,2); end; $$;
alter table public.account add constraint fk_account_created_by foreign key(created_by) references public.staff(id) on delete set null;
alter table public.profiles add constraint fk_profile_staff foreign key(staff_id) references public.staff(id) on delete set null;

-- 007 Auth/RLS
create or replace function public.current_app_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and is_active $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role()='admin',false) $$;
create or replace function public.is_staff_or_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role() in ('admin','staff'),false) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,role) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,''),'@',1)),'staff') on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
do $$ declare t text; begin foreach t in array array['profiles','account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','source_file','import_batch','stg_import_row','data_conflict','completeness_score','staff_alias','client_alias','audit_log','audit_history'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','source_file','import_batch','stg_import_row','data_conflict','completeness_score','staff_alias','client_alias','audit_history'] loop execute format('create policy %I_read on public.%I for select to authenticated using(auth.uid() is not null)',t,t); execute format('create policy %I_insert on public.%I for insert to authenticated with check(public.is_staff_or_admin())',t,t); execute format('create policy %I_update on public.%I for update to authenticated using(public.is_staff_or_admin()) with check(public.is_staff_or_admin())',t,t); execute format('create policy %I_delete on public.%I for delete to authenticated using(public.is_admin())',t,t); end loop; end $$;
create policy profiles_self_or_admin_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_self_or_admin_update on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy profiles_admin_insert on public.profiles for insert to authenticated with check(public.is_admin() or id=auth.uid());
create policy profiles_admin_delete on public.profiles for delete to authenticated using(public.is_admin());
create policy audit_log_admin_read on public.audit_log for select to authenticated using(public.is_admin());
create policy audit_log_staff_insert on public.audit_log for insert to authenticated with check(public.is_staff_or_admin());

-- 008 views
create or replace view public.v_r1_income_statement as select i.id invoice_id,i.invoice_no,i.invoice_date,i.due_date,public.fn_days_outstanding(i.due_date,i.amount_outstanding<=0) days_outstanding,p.id programme_id,p.programme_code,p.title programme_title,c.id client_id,c.company_name client_name,a.code account_code,a.name account_name,rt.code revenue_type_code,rt.name revenue_type_name,i.amount_excl_tax,i.sst_amount,i.sst_rate,i.total_incl_tax,i.amount_collected,i.amount_outstanding,ps.code payment_status_code,ps.name payment_status_name,i.payment_date,pm.code payment_method_code,pm.name payment_method_name,pt.code payment_terms_code,pt.name payment_terms_name,i.quotation_no_ref,i.po_no_ref,i.training_start_date,i.training_end_date,am.full_name account_manager,pic.full_name pic_name,i.is_placeholder,i.is_cancelled,i.source_file,i.source_row_number from public.invoice i left join public.programme p on p.id=i.programme_id left join public.client c on c.id=i.client_id left join public.account a on a.id=i.account_id left join public.revenue_type rt on rt.id=i.revenue_type_id left join public.payment_status ps on ps.id=i.payment_status_id left join public.payment_method pm on pm.id=i.payment_method_id left join public.payment_terms pt on pt.id=i.payment_terms_id left join public.staff am on am.id=p.account_manager_id left join public.staff pic on pic.id=p.pic_id where not i.is_cancelled;
create or replace view public.v_r2_training_stats as select p.id programme_id,p.programme_code,p.title programme_title,c.company_name client_name,tt.name training_type_name,pc.name programme_category_name,p.start_date,p.end_date,p.duration_days,p.no_of_pax,ts.training_date,ts.training_name,ts.company_name training_company,ts.training_category,ts.domain_code,ts.domain_name,ts.workshop_count,ts.training_count,ts.total_count,ts.bumiputera_count,ts.non_bumiputera_count,ts.total_charges_excl_tax,ts.sst_amount training_sst,ts.final_charges_incl_tax,p.total_revenue_excl_tax,p.total_sst_amount,p.total_revenue_incl_tax,p.total_collected,p.total_outstanding,ps.name programme_status_name,am.full_name account_manager,pic.full_name pic_name from public.programme p left join public.client c on c.id=p.client_id left join public.training_type tt on tt.id=p.training_type_id left join public.programme_category pc on pc.id=p.programme_category_id left join public.programme_status ps on ps.id=p.programme_status_id left join public.staff am on am.id=p.account_manager_id left join public.staff pic on pic.id=p.pic_id left join public.training_stat ts on ts.programme_id=p.id;
create or replace view public.v_r3_funnel_pipeline as select o.id opportunity_id,o.opportunity_code,c.company_name client_name,o.project_title,o.project_description,o.opportunity_type,os.name opportunity_status,os.code opportunity_status_code,stm.name speed_to_market,stm.quarter,stm.year,s.name sector_name,o.forecast_value,o.probability_percentage,coalesce(o.weighted_value,public.fn_weighted_forecast(o.forecast_value,o.probability_percentage)) weighted_value,o.secured_value,o.currency,o.expected_close_date,o.actual_close_date,o.po_date,o.po_value,o.is_government,o.is_private,o.is_interco,o.remarks,o.sector_remarks,am.full_name account_manager,sm.full_name salesman,p.id programme_id,p.programme_code linked_programme,o.source_file,o.source_row_number from public.opportunity o left join public.client c on c.id=o.client_id left join public.opportunity_status os on os.id=o.opportunity_status_id left join public.speed_to_market stm on stm.id=o.speed_to_market_id left join public.sector s on s.id=o.sector_id left join public.staff am on am.id=o.account_manager_id left join public.staff sm on sm.id=o.salesman_id left join public.programme p on p.id=o.programme_id;
create or replace view public.v_programme_completeness as select p.id programme_id,p.programme_code,p.title,c.company_name client_name,ps.name programme_status,cs.quotation_score,cs.po_score,cs.invoice_score,cs.payment_score,cs.delivery_score,cs.participant_score,cs.charges_score,cs.pic_score,cs.overall_score,cs.overall_status,cs.missing_components,cs.na_components,cs.evaluated_at,p.total_revenue_excl_tax,p.total_revenue_incl_tax,p.total_collected,p.total_outstanding,p.start_date,p.end_date,p.duration_days,p.no_of_pax,am.full_name account_manager,pic.full_name pic_name from public.programme p left join public.client c on c.id=p.client_id left join public.programme_status ps on ps.id=p.programme_status_id left join public.completeness_score cs on cs.programme_id=p.id left join public.staff am on am.id=p.account_manager_id left join public.staff pic on pic.id=p.pic_id;
create or replace view public.v_financial_dashboard as select 'REVENUE' metric_category,'Total Revenue (excl SST)' metric_name,coalesce(sum(amount_excl_tax),0)::numeric metric_value,count(*) record_count from public.invoice where not is_cancelled and not is_placeholder union all select 'REVENUE','Total Revenue (incl SST)',coalesce(sum(total_incl_tax),0),count(*) from public.invoice where not is_cancelled and not is_placeholder union all select 'COLLECTION','Total Collected',coalesce(sum(amount_collected),0),count(*) from public.invoice where not is_cancelled and not is_placeholder union all select 'COLLECTION','Total Outstanding',coalesce(sum(amount_outstanding),0),count(*) from public.invoice where not is_cancelled and not is_placeholder union all select 'OVERDUE','Overdue Amount',coalesce(sum(amount_outstanding),0),count(*) from public.invoice where not is_cancelled and not is_placeholder and due_date<current_date and amount_outstanding>0 union all select 'FUNNEL','Total Forecast Value',coalesce(sum(forecast_value),0),count(*) from public.opportunity union all select 'FUNNEL','Total Weighted Forecast',coalesce(sum(coalesce(weighted_value,public.fn_weighted_forecast(forecast_value,probability_percentage))),0),count(*) from public.opportunity;
create or replace view public.v_action_item_dashboard as select ai.id action_item_id,ai.action_item_code,c.company_name client_name,p.title programme_title,o.project_title opportunity_title,ai.service,ai.action_description,ai.person_in_charge,ai.person_email,ai.due_date,ai.completed_date,ai.aging_days,ai.priority,ais.name status_name,ais.code status_code,ai.potential_revenue,ai.currency,ai.notes,st.full_name assigned_to,ai.created_at,ai.updated_at from public.action_item ai left join public.client c on c.id=ai.client_id left join public.programme p on p.id=ai.programme_id left join public.opportunity o on o.id=ai.opportunity_id left join public.action_item_status ais on ais.id=ai.action_item_status_id left join public.staff st on st.id=ai.assigned_to_id;
create or replace view public.v_payment_collection as select py.id payment_id,py.payment_reference,i.invoice_no,i.invoice_date,prog.id programme_id,prog.title programme_title,c.company_name client_name,py.payment_date,py.amount,py.sst_amount,py.total_amount,py.currency,py.amount_allocated,py.amount_unallocated,pm.name payment_method,ps.name payment_status,rb.full_name received_by,py.bank_reference,py.cheque_no,py.transaction_id,py.notes from public.payment py left join public.invoice i on i.id=py.invoice_id left join public.programme prog on prog.id=py.programme_id left join public.client c on c.id=py.client_id left join public.payment_method pm on pm.id=py.payment_method_id left join public.payment_status ps on ps.id=py.payment_status_id left join public.staff rb on rb.id=py.received_by_id;
create or replace view public.v_staff_performance as select s.id staff_id,s.full_name,s.email,sr.name role_name,count(distinct p.id) programmes_managed,count(distinct q.id) quotations_prepared,count(distinct o.id) opportunities_owned,count(distinct ai.id) action_items_assigned,coalesce(sum(distinct p.total_revenue_excl_tax),0) total_revenue_managed,coalesce(sum(distinct p.total_collected),0) total_collected_managed from public.staff s left join public.staff_role sr on sr.id=s.role_id left join public.programme p on p.account_manager_id=s.id left join public.quotation q on q.account_manager_id=s.id left join public.opportunity o on o.account_manager_id=s.id left join public.action_item ai on ai.assigned_to_id=s.id where s.is_active group by s.id,s.full_name,s.email,sr.name;

-- 009 indexes/realtime
create index if not exists idx_programme_pic on public.programme(pic_id); create index if not exists idx_programme_account_manager on public.programme(account_manager_id); create index if not exists idx_invoice_due_outstanding on public.invoice(due_date,amount_outstanding) where amount_outstanding>0; create index if not exists idx_payment_reference on public.payment(payment_reference); create index if not exists idx_opportunity_salesman on public.opportunity(salesman_id); create index if not exists idx_action_item_due_status on public.action_item(due_date,action_item_status_id); create index if not exists idx_participant_email on public.participant(email); create index if not exists idx_import_status on public.import_batch(status); create index if not exists idx_conflict_status on public.data_conflict(resolution);
alter publication supabase_realtime add table public.programme; alter publication supabase_realtime add table public.opportunity; alter publication supabase_realtime add table public.action_item; alter publication supabase_realtime add table public.invoice; alter publication supabase_realtime add table public.payment;

-- 010 seed lookup values
insert into public.programme_status(code,name) values ('PLANNED','Planned'),('ONGOING','Ongoing'),('DELIVERED','Delivered'),('COMPLETED','Completed'),('CANCELLED','Cancelled'),('ON_HOLD','On Hold') on conflict(code) do nothing;
insert into public.opportunity_status(code,name) values ('LEAD','Lead'),('QUALIFIED','Qualified'),('PROPOSAL','Proposal'),('NEGOTIATION','Negotiation'),('CONTRACT_SIGNED','Contract Signed'),('WON','Won'),('LOST','Lost') on conflict(code) do nothing;
insert into public.payment_status(code,name) values ('UNPAID','Unpaid'),('PARTIAL','Partial'),('PAID','Paid'),('OVERDUE','Overdue'),('PENDING','Pending'),('COMPLETED','Completed'),('FAILED','Failed') on conflict(code) do nothing;
insert into public.payment_method(code,name) values ('BANK_TRANSFER','Bank Transfer'),('CHEQUE','Cheque'),('CARD','Card'),('CASH','Cash'),('OTHER','Other') on conflict(code) do nothing;
insert into public.quotation_status(code,name) values ('DRAFT','Draft'),('SENT','Sent'),('ACCEPTED','Accepted'),('REJECTED','Rejected'),('EXPIRED','Expired') on conflict(code) do nothing;
insert into public.quotation_type(code,name) values ('TRAINING','Training'),('CONSULTING','Consulting'),('OTHER','Other') on conflict(code) do nothing;
insert into public.action_item_status(code,name) values ('OPEN','Open'),('IN_PROGRESS','In Progress'),('COMPLETED','Completed'),('CANCELLED','Cancelled') on conflict(code) do nothing;
insert into public.programme_category(code,name) values ('PUBLIC','Public Training'),('INHOUSE','In-House'),('CUSTOM','Custom Programme'),('INTERNAL','Internal') on conflict(code) do nothing;
insert into public.service_type(code,name) values ('TRAINING','Training'),('CONSULTING','Consulting'),('WORKSHOP','Workshop'),('OTHER','Other') on conflict(code) do nothing;
insert into public.revenue_type(code,name) values ('TRAINING','Training Revenue'),('CONSULTING','Consulting Revenue'),('OTHER','Other Revenue') on conflict(code) do nothing;
insert into public.payment_terms(code,name,days) values ('COD','Cash on Delivery',0),('NET30','30 Days',30),('NET60','60 Days',60),('NET90','90 Days',90) on conflict(code) do nothing;

-- 011 migration support
create table public.migration_id_map (id bigint generated always as identity primary key,source_system text not null,entity_type text not null,legacy_id text not null,target_id bigint not null,source_file text,source_row_number integer,created_at timestamptz not null default now(),unique(source_system,entity_type,legacy_id));
create index idx_migration_id_map_lookup on public.migration_id_map(source_system,entity_type,legacy_id); alter table public.migration_id_map enable row level security;
create policy migration_map_admin_read on public.migration_id_map for select to authenticated using(public.is_admin()); create policy migration_map_admin_write on public.migration_id_map for all to authenticated using(public.is_admin()) with check(public.is_admin());
create or replace function public.record_audit(p_entity_type text,p_entity_id bigint,p_action text,p_old jsonb,p_new jsonb,p_metadata jsonb default '{}'::jsonb) returns bigint language plpgsql security definer set search_path=public as $$ declare v_id bigint; begin insert into public.audit_log(entity_type,entity_id,action,actor_id,old_data,new_data,metadata) values(p_entity_type,p_entity_id,p_action,auth.uid(),p_old,p_new,p_metadata) returning id into v_id; return v_id; end; $$;

-- 012 Storage
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('pms-documents','pms-documents',false,52428800,array['application/pdf','image/png','image/jpeg','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','text/csv']) on conflict(id) do update set public=false;
create policy pms_documents_select on storage.objects for select to authenticated using(bucket_id='pms-documents' and auth.uid() is not null);
create policy pms_documents_insert on storage.objects for insert to authenticated with check(bucket_id='pms-documents' and public.is_staff_or_admin());
create policy pms_documents_update on storage.objects for update to authenticated using(bucket_id='pms-documents' and public.is_staff_or_admin()) with check(bucket_id='pms-documents' and public.is_staff_or_admin());
create policy pms_documents_delete on storage.objects for delete to authenticated using(bucket_id='pms-documents' and public.is_admin());

commit;

-- Post-install verification queries:
-- select table_name from information_schema.tables where table_schema='public' order by table_name;
-- select * from public.v_financial_dashboard;
-- select * from public.v_r1_income_statement limit 10;
-- select * from public.v_r2_training_stats limit 10;
-- select * from public.v_r3_funnel_pipeline limit 10;
