-- Phase 1 / 005: funnel, action, training, participants, audit/import
create table public.opportunity (
 id bigint generated always as identity primary key, opportunity_code varchar(50), client_id bigint not null references public.client(id) on delete restrict, programme_id bigint references public.programme(id) on delete set null, opportunity_status_id bigint references public.opportunity_status(id) on delete set null, speed_to_market_id bigint references public.speed_to_market(id) on delete set null, sector_id bigint references public.sector(id) on delete set null, account_manager_id bigint references public.staff(id) on delete set null, salesman_id bigint references public.staff(id) on delete set null,
 project_title varchar(500) not null, project_description text, opportunity_type varchar(100), forecast_value numeric(18,2), probability_percentage numeric(5,2), weighted_value numeric(18,2), secured_value numeric(18,2), currency varchar(3) not null default 'MYR', expected_close_date date, actual_close_date date, po_date date, po_value numeric(18,2), is_government boolean default false, is_private boolean default false, is_interco boolean default false, remarks text, sector_remarks varchar(255),
 source_file text, source_row_number integer, import_batch_id bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by bigint references public.staff(id) on delete set null, updated_by bigint references public.staff(id) on delete set null,
 constraint chk_opp_prob check(probability_percentage is null or probability_percentage between 0 and 100), constraint chk_opp_money check(coalesce(forecast_value,0)>=0 and coalesce(weighted_value,0)>=0 and coalesce(secured_value,0)>=0)
);
create index idx_opportunity_client on public.opportunity(client_id); create index idx_opportunity_programme on public.opportunity(programme_id); create index idx_opportunity_status on public.opportunity(opportunity_status_id); create index idx_opportunity_close on public.opportunity(expected_close_date); create index idx_opportunity_match on public.opportunity(client_id,project_title,forecast_value);

create table public.action_item (
 id bigint generated always as identity primary key, action_item_code varchar(50), client_id bigint references public.client(id) on delete set null, programme_id bigint references public.programme(id) on delete set null, opportunity_id bigint references public.opportunity(id) on delete set null, invoice_id bigint references public.invoice(id) on delete set null, assigned_to_id bigint references public.staff(id) on delete set null, action_item_status_id bigint references public.action_item_status(id) on delete set null, service_type_id bigint references public.service_type(id) on delete set null, service varchar(255), action_description text not null, person_in_charge varchar(100), person_email varchar(255), due_date date, completed_date date, potential_revenue numeric(18,2), currency varchar(3) not null default 'MYR', aging_days integer, priority varchar(20) not null default 'MEDIUM', notes text, source_file text, source_row_number integer, import_batch_id bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by bigint references public.staff(id) on delete set null, updated_by bigint references public.staff(id) on delete set null,
 constraint chk_action_priority check(priority in ('LOW','MEDIUM','HIGH','CRITICAL')), constraint chk_action_money check(potential_revenue is null or potential_revenue>=0)
);
create index idx_action_programme on public.action_item(programme_id); create index idx_action_status on public.action_item(action_item_status_id); create index idx_action_due on public.action_item(due_date); create index idx_action_assigned on public.action_item(assigned_to_id);

create table public.training_stat (
 id bigint generated always as identity primary key, programme_id bigint not null references public.programme(id) on delete restrict, training_type_id bigint references public.training_type(id) on delete set null, training_date date, training_name varchar(500), company_name varchar(255), training_category varchar(100), duration_days numeric(5,2), domain_code varchar(50), domain_name varchar(100), workshop_count integer default 0, training_count integer default 0, total_count integer default 0, bumiputera_count integer default 0, non_bumiputera_count integer default 0, total_charges_excl_tax numeric(18,2), sst_amount numeric(18,2), final_charges_incl_tax numeric(18,2), currency varchar(3) default 'MYR', source_file text, source_row_number integer, import_batch_id bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by bigint references public.staff(id) on delete set null, updated_by bigint references public.staff(id) on delete set null,
 constraint chk_training_counts check(workshop_count>=0 and training_count>=0 and total_count>=0 and bumiputera_count>=0 and non_bumiputera_count>=0)
);
create index idx_training_stat_programme on public.training_stat(programme_id); create index idx_training_stat_date on public.training_stat(training_date); create index idx_training_stat_match on public.training_stat(programme_id,training_date,domain_code);

create table public.participant (
 id bigint generated always as identity primary key, programme_id bigint not null references public.programme(id) on delete restrict, training_stat_id bigint references public.training_stat(id) on delete set null, full_name varchar(255) not null, identification_no varchar(50), cert_no varchar(100), email varchar(255), phone varchar(50), designation varchar(100), department varchar(100), organization varchar(255), is_bumiputera boolean, gender varchar(10), attendance_status varchar(50) default 'ATTENDED', cert_issued boolean default false, cert_issue_date date, source_file text, source_row_number integer, import_batch_id bigint, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by bigint references public.staff(id) on delete set null, updated_by bigint references public.staff(id) on delete set null
);
create index idx_participant_programme on public.participant(programme_id); create index idx_participant_name on public.participant(full_name); create index idx_participant_cert on public.participant(cert_no);

create table public.source_file (
 id bigint generated always as identity primary key, file_name varchar(255) not null, file_path varchar(500), file_hash varchar(64) not null, file_size_bytes bigint, file_type varchar(50), upload_date timestamptz not null default now(), uploaded_by_id bigint references public.staff(id) on delete set null, description text, is_processed boolean not null default false, processed_at timestamptz
);
create index idx_source_file_hash on public.source_file(file_hash);
create table public.import_batch (
 id bigint generated always as identity primary key, batch_code varchar(50) not null unique, source_file_id bigint references public.source_file(id) on delete set null, import_type varchar(50) not null, table_target varchar(100) not null, records_total integer default 0, records_inserted integer default 0, records_updated integer default 0, records_skipped integer default 0, records_failed integer default 0, records_in_review integer default 0, status varchar(50) default 'PENDING', start_time timestamptz, end_time timestamptz, notes text, error_log text, imported_by_id bigint references public.staff(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.stg_import_row (
 id bigint generated always as identity primary key, import_batch_id bigint not null references public.import_batch(id) on delete cascade, source_file_id bigint references public.source_file(id) on delete set null, source_row_number integer not null, entity_type varchar(100) not null, raw_data jsonb not null, normalized_data jsonb, business_key text, validation_status varchar(30) not null default 'PENDING', validation_errors jsonb not null default '[]'::jsonb, target_id bigint, created_at timestamptz not null default now()
);
create index idx_stg_batch on public.stg_import_row(import_batch_id); create index idx_stg_business_key on public.stg_import_row(entity_type,business_key);
create table public.data_conflict (
 id bigint generated always as identity primary key, import_batch_id bigint references public.import_batch(id) on delete set null, entity_type varchar(100) not null, source_row_number integer, existing_record_id bigint, conflict_type varchar(50) not null, source_data jsonb not null default '{}'::jsonb, existing_data jsonb not null default '{}'::jsonb, resolution varchar(30) default 'PENDING', resolved_record_id bigint, resolved_by uuid references auth.users(id) on delete set null, resolution_notes text, created_at timestamptz not null default now(), resolved_at timestamptz
);
create table public.completeness_score (
 id bigint generated always as identity primary key, programme_id bigint references public.programme(id) on delete cascade, quotation_score numeric(5,2), po_score numeric(5,2), invoice_score numeric(5,2), payment_score numeric(5,2), delivery_score numeric(5,2), participant_score numeric(5,2), charges_score numeric(5,2), pic_score numeric(5,2), overall_score numeric(5,2), overall_status varchar(30), missing_components jsonb not null default '[]'::jsonb, na_components jsonb not null default '[]'::jsonb, evaluated_at timestamptz not null default now(), evaluated_by uuid references auth.users(id) on delete set null, unique(programme_id)
);
create table public.staff_alias (id bigint generated always as identity primary key, source_name text not null unique, staff_id bigint references public.staff(id) on delete set null, source_file text, created_at timestamptz not null default now());
create table public.client_alias (id bigint generated always as identity primary key, source_name text not null unique, client_id bigint references public.client(id) on delete set null, source_file text, created_at timestamptz not null default now());
create table public.audit_log (id bigint generated always as identity primary key, entity_type text not null, entity_id bigint, action text not null, actor_id uuid references auth.users(id) on delete set null, old_data jsonb, new_data jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.audit_history (id bigint generated always as identity primary key, programme_id bigint references public.programme(id) on delete set null, action text not null, entity text, description text, actor_id uuid references auth.users(id) on delete set null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index idx_audit_log_entity on public.audit_log(entity_type,entity_id); create index idx_audit_log_created on public.audit_log(created_at);
