-- Phase 1 / 006: MySQL ON UPDATE -> PostgreSQL triggers; business functions
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['profiles','account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','import_batch'] loop execute format('drop trigger if exists %I on public.%I',t||'_updated_at',t); execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()',t||'_updated_at',t); end loop; end $$;

create or replace function public.fn_days_outstanding(p_due_date date,p_paid boolean default false) returns integer language sql stable as $$ select case when p_due_date is null or p_paid then null else current_date-p_due_date end $$;
create or replace function public.fn_weighted_forecast(p_forecast numeric,p_probability numeric) returns numeric language sql immutable as $$ select case when p_forecast is null or p_probability is null then null else round(p_forecast*greatest(least(p_probability,100),0)/100,2) end $$;
create or replace function public.fn_calc_sst(p_base_amount numeric,p_sst_rate numeric default .08) returns numeric language sql immutable as $$ select case when p_base_amount is null or p_sst_rate is null then null else round(p_base_amount*p_sst_rate,2) end $$;
create or replace function public.fn_calc_total_incl_sst(p_base_amount numeric,p_sst_amount numeric) returns numeric language sql immutable as $$ select case when p_base_amount is null then null else p_base_amount+coalesce(p_sst_amount,0) end $$;

create or replace function public.fn_refresh_invoice(p_invoice_id bigint) returns void language plpgsql security definer set search_path=public as $$ declare v_collected numeric; begin select coalesce(sum(coalesce(amount,0)),0) into v_collected from public.payment p left join public.payment_status ps on ps.id=p.payment_status_id where p.invoice_id=p_invoice_id and coalesce(ps.code,'') in ('PAID','COMPLETED','SUCCESS'); update public.invoice i set amount_collected=least(v_collected,coalesce(i.total_incl_tax,i.amount_excl_tax,0)), amount_outstanding=greatest(coalesce(i.total_incl_tax,i.amount_excl_tax,0)-least(v_collected,coalesce(i.total_incl_tax,i.amount_excl_tax,0)),0), days_outstanding=public.fn_days_outstanding(i.due_date,v_collected>=coalesce(i.total_incl_tax,i.amount_excl_tax,0)) where i.id=p_invoice_id; end; $$;
create or replace function public.trg_payment_refresh_invoice() returns trigger language plpgsql security definer set search_path=public as $$ begin if tg_op='DELETE' then perform public.fn_refresh_invoice(old.invoice_id); else perform public.fn_refresh_invoice(new.invoice_id); if tg_op='UPDATE' and old.invoice_id is distinct from new.invoice_id then perform public.fn_refresh_invoice(old.invoice_id); end if; end if; return coalesce(new,old); end; $$;
drop trigger if exists payment_refresh_invoice on public.payment; create trigger payment_refresh_invoice after insert or update or delete on public.payment for each row execute function public.trg_payment_refresh_invoice();

create or replace function public.fn_refresh_programme(p_programme_id bigint) returns void language plpgsql security definer set search_path=public as $$ begin update public.programme p set total_revenue_excl_tax=coalesce((select sum(i.amount_excl_tax) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0), total_sst_amount=coalesce((select sum(i.sst_amount) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0), total_revenue_incl_tax=coalesce((select sum(i.total_incl_tax) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0), total_collected=coalesce((select sum(i.amount_collected) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0), total_outstanding=coalesce((select sum(i.amount_outstanding) from public.invoice i where i.programme_id=p.id and not i.is_cancelled and not i.is_placeholder),0) where p.id=p_programme_id; end; $$;
create or replace function public.trg_invoice_refresh_programme() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.fn_refresh_programme(coalesce(new.programme_id,old.programme_id)); return coalesce(new,old); end; $$;
drop trigger if exists invoice_refresh_programme on public.invoice; create trigger invoice_refresh_programme after insert or update or delete on public.invoice for each row execute function public.trg_invoice_refresh_programme();

create or replace function public.fn_programme_completeness(p_programme_id bigint) returns numeric language plpgsql security definer set search_path=public as $$ declare n int:=0; s int:=0; begin select count(*) into n from public.quotation where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.purchase_order where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.invoice where programme_id=p_programme_id and not is_placeholder and not is_cancelled; if n>0 then s:=s+1; end if; select count(*) into n from public.payment where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.training_stat where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.participant where programme_id=p_programme_id; if n>0 then s:=s+1; end if; select count(*) into n from public.invoice where programme_id=p_programme_id and coalesce(amount_excl_tax,0)>0; if n>0 then s:=s+1; end if; select count(*) into n from public.programme where id=p_programme_id and pic_id is not null; if n>0 then s:=s+1; end if; insert into public.completeness_score(programme_id,overall_score,overall_status,evaluated_at) values(p_programme_id,round(s*12.5,2),case when s=8 then 'COMPLETE' when s>=6 then 'PARTIAL' else 'INCOMPLETE' end,now()) on conflict(programme_id) do update set overall_score=excluded.overall_score,overall_status=excluded.overall_status,evaluated_at=now(); return round(s*12.5,2); end; $$;

alter table public.account add constraint fk_account_created_by foreign key(created_by) references public.staff(id) on delete set null;
alter table public.profiles add constraint fk_profile_staff foreign key(staff_id) references public.staff(id) on delete set null;
