-- Phase 1 / 007: Supabase Auth profile provisioning + RLS
create or replace function public.current_app_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and is_active $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role()='admin',false) $$;
create or replace function public.is_staff_or_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role() in ('admin','staff'),false) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,role) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(coalesce(new.email,''),'@',1)),'staff') on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Every application table is protected. Viewer is read-only; staff/admin may mutate; admin may delete.
do $$ declare t text; begin foreach t in array array['profiles','account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','source_file','import_batch','stg_import_row','data_conflict','completeness_score','staff_alias','client_alias','audit_log','audit_history'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['account_type','staff_role','sector','training_type','payment_method','payment_status','quotation_type','quotation_status','programme_status','project_status','opportunity_status','action_item_status','payment_terms','speed_to_market','programme_category','service_type','revenue_type','account','staff','client','client_contact','programme','quotation','purchase_order','invoice','payment','opportunity','action_item','training_stat','participant','source_file','import_batch','stg_import_row','data_conflict','completeness_score','staff_alias','client_alias','audit_history'] loop execute format('create policy %I_read on public.%I for select to authenticated using(auth.uid() is not null)',t,t); execute format('create policy %I_insert on public.%I for insert to authenticated with check(public.is_staff_or_admin())',t,t); execute format('create policy %I_update on public.%I for update to authenticated using(public.is_staff_or_admin()) with check(public.is_staff_or_admin())',t,t); execute format('create policy %I_delete on public.%I for delete to authenticated using(public.is_admin())',t,t); end loop; end $$;
create policy profiles_self_or_admin_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_self_or_admin_update on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy profiles_admin_insert on public.profiles for insert to authenticated with check(public.is_admin() or id=auth.uid());
create policy profiles_admin_delete on public.profiles for delete to authenticated using(public.is_admin());
create policy audit_log_admin_read on public.audit_log for select to authenticated using(public.is_admin());
create policy audit_log_staff_insert on public.audit_log for insert to authenticated with check(public.is_staff_or_admin());
