import React, { useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet';
import { toast } from 'sonner';
import PageHeader from '@/components/PageHeader';
import StatCard from '@/components/StatCard';
import DataTable from '@/components/DataTable';
import StatusBadge from '@/components/StatusBadge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { formatDate } from '@/lib/mockData';
import { insert, list, subscribe, update } from '@/lib/pmsRepository';
import { AlarmClock, CheckCircle2, CheckSquare, ListTodo, Plus } from 'lucide-react';

const mapItem = (a) => ({ id:a.id, title:a.action_description||a.action_item_code||'—', relatedTo:a.programme?.programme_code||a.client?.company_name||'General', programmeCode:a.programme?.programme_code||'—', owner:a.person_in_charge||'Unassigned', dueDate:a.due_date, priority:a.priority||'Medium', status:a.action_item_status?.name||a.action_item_status?.code||'—' });
const overdue=(date,status)=>status!=='Completed'&&date&&new Date(date)<new Date();

export default function ActionItemsPage(){
 const [items,setItems]=useState([]); const [statuses,setStatuses]=useState([]); const [open,setOpen]=useState(false); const [form,setForm]=useState({title:'',relatedTo:'',owner:'',dueDate:'',priority:'Medium'});
 const load=async()=>{try{const {data}=await list('action_item',{select:'*,programme(programme_code),client(company_name),action_item_status(name,code)',pageSize:500,orderBy:'due_date',ascending:true});setItems(data.map(mapItem));}catch(e){toast.error(`Unable to load action items: ${e.message}`);}};
 const loadStatuses=async()=>{try{const {data}=await list('action_item_status',{pageSize:100,orderBy:'id',ascending:true});setStatuses(data||[]);}catch(e){toast.error(`Unable to load action-item statuses: ${e.message}`);}};
 useEffect(()=>{load();loadStatuses();return subscribe('action_item',load);},[]);
 const openStatus=useMemo(()=>statuses.find(s=>/open/i.test(s.code||s.name||''))||statuses[0],[statuses]); const doneStatus=useMemo(()=>statuses.find(s=>/completed|closed|done/i.test(s.code||s.name||'')),[statuses]);
 const openCount=items.filter(a=>! /completed|closed|done/i.test(a.status)).length; const overdueCount=items.filter(a=>overdue(a.dueDate,a.status)).length; const completedCount=items.length-openCount; const dueThisWeek=items.filter(a=>! /completed|closed|done/i.test(a.status)&&a.dueDate&&new Date(a.dueDate)<=new Date('2026-08-31T23:59:59')).length;
 const handleCreate=async e=>{e.preventDefault();try{await insert('action_item',{action_description:form.title.trim(),person_in_charge:form.owner.trim()||null,due_date:form.dueDate,priority:form.priority,action_item_status_id:openStatus?.id||null});setForm({title:'',relatedTo:'',owner:'',dueDate:'',priority:'Medium'});setOpen(false);toast.success('Action item created.');await load();}catch(err){toast.error(`Unable to create action item: ${err.message}`);}};
 const markDone=async id=>{if(!doneStatus){toast.error('Completed status is not configured.');return;}try{await update('action_item',id,{action_item_status_id:doneStatus.id,completed_date:new Date().toISOString().slice(0,10)});toast.success('Action item marked as completed.');}catch(e){toast.error(`Unable to complete action item: ${e.message}`);}};
 const statusesForFilter=useMemo(()=>[...new Set(items.map(a=>a.status).filter(Boolean))],[items]);
 const columns=[{key:'title',label:'Action Item',render:a=><div className='min-w-56'><p className={`font-medium ${/completed|closed|done/i.test(a.status)?'text-slate-400 line-through':'text-slate-800'}`}>{a.title}</p><p className='text-xs text-slate-400'>{a.relatedTo}</p></div>},{key:'programmeCode',label:'Programme',className:'whitespace-nowrap font-medium text-violet-700'},{key:'owner',label:'Owner',className:'whitespace-nowrap'},{key:'dueDate',label:'Due Date',className:'whitespace-nowrap',render:a=><span className={overdue(a.dueDate,a.status)?'font-medium text-red-600':'text-slate-500'}>{formatDate(a.dueDate)}{overdue(a.dueDate,a.status)&&' · overdue'}</span>},{key:'priority',label:'Priority',render:a=><StatusBadge status={a.priority}/>},{key:'status',label:'Status',render:a=><StatusBadge status={a.status}/>},{key:'actions',label:'',render:a=>! /completed|closed|done/i.test(a.status)?<Button variant='ghost' size='sm' className='text-violet-700' onClick={()=>markDone(a.id)}><CheckCircle2 className='mr-1.5 h-4 w-4'/> Done</Button>:null}];
 return <div><Helmet><title>Action Items — MIMOS Academy PMS</title></Helmet><PageHeader title='Action Items' description='Live team follow-ups and operational tasks.'><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className='bg-violet-600 hover:bg-violet-700'><Plus className='mr-2 h-4 w-4'/> New Action Item</Button></DialogTrigger><DialogContent className='sm:max-w-md'><DialogHeader><DialogTitle>New action item</DialogTitle><DialogDescription>Create a live task in Supabase.</DialogDescription></DialogHeader><form onSubmit={handleCreate} className='space-y-4'><div className='space-y-2'><Label htmlFor='ai-title'>Title</Label><Input id='ai-title' required value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></div><div className='space-y-2'><Label htmlFor='ai-related'>Related to</Label><Input id='ai-related' value={form.relatedTo} onChange={e=>setForm(f=>({...f,relatedTo:e.target.value}))}/></div><div className='grid grid-cols-2 gap-4'><div className='space-y-2'><Label htmlFor='ai-owner'>Owner</Label><Input id='ai-owner' value={form.owner} onChange={e=>setForm(f=>({...f,owner:e.target.value}))}/></div><div className='space-y-2'><Label htmlFor='ai-due'>Due date</Label><Input id='ai-due' type='date' required value={form.dueDate} onChange={e=>setForm(f=>({...f,dueDate:e.target.value}))}/></div></div><div className='space-y-2'><Label>Priority</Label><Select value={form.priority} onValueChange={v=>setForm(f=>({...f,priority:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value='High'>High</SelectItem><SelectItem value='Medium'>Medium</SelectItem><SelectItem value='Low'>Low</SelectItem></SelectContent></Select></div><DialogFooter><Button type='submit' className='bg-violet-600 hover:bg-violet-700'>Create item</Button></DialogFooter></form></DialogContent></Dialog></PageHeader><div className='mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4'><StatCard title='Open Items' value={openCount} icon={ListTodo} tone='violet' hint='live'/><StatCard title='Overdue' value={overdueCount} icon={AlarmClock} tone='red' deltaDirection='down' delta={overdueCount?'Act now':undefined} hint='past due'/><StatCard title='Due This Week' value={dueThisWeek} icon={CheckSquare} tone='amber' hint='by 31 Aug 2026'/><StatCard title='Completed' value={completedCount} icon={CheckCircle2} tone='emerald' hint='closed items'/></div><DataTable columns={columns} data={items} searchKeys={['title','relatedTo','owner']} searchPlaceholder='Search action items…' filters={[{key:'status',label:'Status',options:statusesForFilter},{key:'priority',label:'Priority',options:['High','Medium','Low']}]} emptyTitle='No action items found' emptyDescription='No live action items exist in Supabase yet.'/></div>;
}
